import { ClothSimulationConfig } from '../interfaces/cloth-simulation-config.interface';

export const CLOTH_SIMULATION_CONFIG: ClothSimulationConfig = {
  accuracy: 10,
  bounce: 0.4,
  fontFamily: 'Arial Black, Impact, Haettenschweiler, sans-serif',
  fontScale: 0.55,
  fontWeight: 900,
  friction: 0.992,
  gravity: 520,
  lineWidthDivisor: 7,
  maxDpr: 2,
  maxFontSize: 720,
  maxSpacing: 18,
  minFontSize: 48,
  minSpacing: 10,
  minTopPadding: 24,
  pointerCutMultiplier: 1.2,
  pointerInfluenceMultiplier: 4.6,
  sampleAlphaThreshold: 8,
  spacingDivisor: 18,
  strokeStyle: '#5a616b',
  targetHeightRatio: 0.65,
  targetText: 'DRAKE',
  targetWidthRatio: 0.95,
  tearDistanceMultiplier: 9,
  textPadding: 36,
  topPaddingRatio: 0.08,
};
