import { TetrisGameConfig } from '../interfaces/tetris-game-config.interface';

export const TETRIS_GAME_CONFIG: TetrisGameConfig = {
  gridWidth: 10,
  gridHeight: 20,
  initialDropIntervalMs: 1000,
  previewBlockSize: 32,
  previewCanvasCells: 5,
  scoreFont: "'Press Start 2P', monospace",
  scoreFontSize: 12,
  gameOverFont: "'Press Start 2P', monospace",
  gameOverFontSize: 28,
  gameOverSubFont: "'Press Start 2P', monospace",
  gameOverSubFontSize: 10,
  blockStrokeColor: 'rgba(80, 10, 40, 0.4)',
  blockHighlightAlpha: 0.4,
  blockShadowAlpha: 0.25,
  canvasBackgroundColor: '#1a0612',
  gridLineColor: 'rgba(255, 150, 200, 0.06)',
  previewBackgroundColor: '#1a0612',
  scoreFontColor: '#ffb6d9',
  gameOverOverlayColor: 'rgba(20, 2, 12, 0.85)',
  gameOverFontColor: '#ff69b4',
  scoreX: 10,
  scoreY: 30,
  linePoints: [0, 40, 100, 300, 1200],
  speedUpThreshold: 5,
  speedUpDivisor: 2,
  musicSpeedIncrement: 0.25,
  musicMaxSpeed: 5.0,
  musicVolume: 0.1,
  touchSwipeThreshold: 0.75,
  touchTapThreshold: 0.25,
  blockEffectGravity: -0.005,
  blockEffectMinSpeedX: -0.8,
  blockEffectMaxSpeedX: 0.8,
  blockEffectMinSpeedY: -0.8,
  blockEffectMaxSpeedY: -0.2,
  stackHeightThreshold: 8,
  stackHeightPenaltyPerRow: 1000,
};
