import { PidPresetDefinition } from '../interfaces/pid-preset-definition.interface';
import { PidPresetName } from '../types/pid-preset-name.type';

export const PID_PRESETS: Record<PidPresetName, PidPresetDefinition> = {
  balanced: {
    controller: { kp: 110, ki: 12, kd: 18 },
    plant: { mass: 1.2, damping: 0.8, spring: 10 },
    nonIdeal: {
      saturationEnabled: true,
      actuatorLimit: 15,
      antiWindupEnabled: true,
      noiseEnabled: false,
      noiseSigma: 0.05,
      delayEnabled: false,
      delayMs: 120,
      derivativeFilterEnabled: true,
      derivativeTau: 0.03,
    },
  },
  p_only: {
    controller: { kp: 190, ki: 0, kd: 0 },
    plant: { mass: 1.2, damping: 0.4, spring: 10 },
    nonIdeal: {
      saturationEnabled: true,
      actuatorLimit: 15,
      antiWindupEnabled: true,
      noiseEnabled: false,
      noiseSigma: 0.05,
      delayEnabled: false,
      delayMs: 120,
      derivativeFilterEnabled: true,
      derivativeTau: 0.03,
    },
  },
  pi: {
    controller: { kp: 90, ki: 18, kd: 0 },
    plant: { mass: 1.2, damping: 0.8, spring: 10 },
    nonIdeal: {
      saturationEnabled: true,
      actuatorLimit: 15,
      antiWindupEnabled: true,
      noiseEnabled: false,
      noiseSigma: 0.05,
      delayEnabled: false,
      delayMs: 120,
      derivativeFilterEnabled: true,
      derivativeTau: 0.03,
    },
  },
  pd: {
    controller: { kp: 160, ki: 0, kd: 26 },
    plant: { mass: 1.2, damping: 0.8, spring: 10 },
    nonIdeal: {
      saturationEnabled: true,
      actuatorLimit: 15,
      antiWindupEnabled: true,
      noiseEnabled: false,
      noiseSigma: 0.05,
      delayEnabled: false,
      delayMs: 120,
      derivativeFilterEnabled: true,
      derivativeTau: 0.03,
    },
  },
  aggressive: {
    controller: { kp: 220, ki: 28, kd: 24 },
    plant: { mass: 1.2, damping: 0.7, spring: 10 },
    nonIdeal: {
      saturationEnabled: true,
      actuatorLimit: 18,
      antiWindupEnabled: true,
      noiseEnabled: false,
      noiseSigma: 0.05,
      delayEnabled: false,
      delayMs: 120,
      derivativeFilterEnabled: true,
      derivativeTau: 0.02,
    },
  },
  noisy_sensor: {
    controller: { kp: 120, ki: 10, kd: 22 },
    plant: { mass: 1.2, damping: 0.8, spring: 10 },
    nonIdeal: {
      saturationEnabled: true,
      actuatorLimit: 15,
      antiWindupEnabled: true,
      noiseEnabled: true,
      noiseSigma: 0.06,
      delayEnabled: false,
      delayMs: 120,
      derivativeFilterEnabled: true,
      derivativeTau: 0.06,
    },
  },
  has_delay: {
    controller: { kp: 130, ki: 16, kd: 24 },
    plant: { mass: 1.2, damping: 0.9, spring: 10 },
    nonIdeal: {
      saturationEnabled: true,
      actuatorLimit: 15,
      antiWindupEnabled: true,
      noiseEnabled: false,
      noiseSigma: 0.05,
      delayEnabled: true,
      delayMs: 160,
      derivativeFilterEnabled: true,
      derivativeTau: 0.04,
    },
  },
};
