import { FlappyBirdGameConfig } from '../interfaces/flappy-bird-game-config.interface';

export const FLAPPY_BIRD_GAME_CONFIG: FlappyBirdGameConfig = {
  backgroundScrollFactor: 0.00125,
  baseGroundSpeed: 2,
  basePipeSpeed: 2,
  birdFlapCadence: 2,
  birdFrames: [
    { height: 64, width: 90, x: 1, y: 0 },
    { height: 64, width: 90, x: 93, y: 0 },
    { height: 64, width: 90, x: 185, y: 0 },
  ],
  birdGravity: 0.6,
  birdHeight: 30,
  birdJumpLift: -15,
  birdStartX: 50,
  birdStartY: 300,
  birdVelocityDamping: 0.9,
  birdWidth: 40,
  fontFamily: 'FlappyBirdy',
  gameHeight: 600,
  gameWidth: 350,
  groundCollisionHeight: 90,
  groundDrawHeight: 110,
  groundDrawY: 575,
  groundSourceHeight: 110,
  groundSourceWidth: 330,
  groundSourceX: 570,
  groundSourceY: 10,
  groundTileStep: 325,
  pipeLeadDistance: 80,
  pipeMaxTop: 350,
  pipeMinTop: 100,
  pipeNarrowGap: 120,
  pipeNormalGap: 150,
  pipeWidth: 52,
  scoreFontSize: 72,
};
