import { TetrisGameConfig } from '../interfaces/tetris-game-config.interface';

export const TETRIS_GAME_CONFIG: TetrisGameConfig = {
  gridWidth: 10,
  gridHeight: 20,
  initialDropIntervalMs: 1000,
  previewBlockSize: 32,
  previewCanvasCells: 5,
  scoreFont: "'Press Start 2P', monospace",
  scoreFontSize: 12,
  gameOverFont: "'Press Start 2P', monospace",
  gameOverFontSize: 28,
  gameOverSubFont: "'Press Start 2P', monospace",
  gameOverSubFontSize: 10,
  blockStrokeColor: 'rgba(0, 0, 0, 0.4)',
  blockHighlightAlpha: 0.35,
  blockShadowAlpha: 0.3,
  canvasBackgroundColor: '#1a1a2e',
  gridLineColor: 'rgba(255, 255, 255, 0.04)',
  previewBackgroundColor: '#1a1a2e',
  scoreFontColor: '#e0e0e0',
  gameOverOverlayColor: 'rgba(0, 0, 0, 0.8)',
  gameOverFontColor: '#fff',
  scoreX: 10,
  scoreY: 30,
  linePoints: [0, 40, 100, 300, 1200],
  speedUpThreshold: 5,
  speedUpDivisor: 2,
  musicSpeedIncrement: 0.25,
  musicMaxSpeed: 5.0,
  musicVolume: 0.1,
  touchSwipeThreshold: 0.75,
  touchTapThreshold: 0.25,
  blockEffectGravity: 0.3,
  blockEffectMinSpeedX: -3,
  blockEffectMaxSpeedX: 3,
  blockEffectMinSpeedY: -22,
  blockEffectMaxSpeedY: -4,
};
